# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_ALPHAS=QWERTY
MIRYOKU_EXTRA=COLEMAKDH
MIRYOKU_NAV=VI
MIRYOKU_KMONAD_OS=MAC
MIRYOKU_MAPPING=LITE
MIRYOKU_ALPHAS=
MIRYOKU_NAV=
MIRYOKU_CLIPBOARD=
MIRYOKU_LAYERS=
MIRYOKU_MAPPING=
MIRYOKU_KMONAD_OS=
