# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build All'
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["qwerty", "qwertz", "workman"]'
      nav: '["default", "invertedt", "vi"]'
      clipboard: '["default", "fun", "mac", "win"]'
      layers: '["default", "flip"]'
      mapping: '["default", "noreverseangle", "lite"]'
      kmonad_os: '["default", "mac", "win"]'
