name: 'Build KBD Custom'
on:
  push:
    branches:
      - '*' # Trigger on push to any branch

jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["QWERTY"]'
      nav: '["VI"]'
      clipboard: '["default"]' # Using default as not specified in the request
      layers: '["default"]'    # Using default as not specified in the request
      mapping: '["LITE"]'
      kmonad_os: '["MAC"]'
      rules: |
        MIRYOKU_ALPHAS=QWERTY
        MIRYOKU_EXTRA=COLEMAKDH
        MIRYOKU_NAV=VI
        MIRYOKU_KMONAD_OS=MAC
        MIRYOKU_MAPPING=LITE
      custom_config: 'default' # Using default as not specified in the request 